import piolho1 from "../images/piolho1.jpg"
import piolho2 from "../images/piolho2.jpg"
import piolho3 from "../images/piolho3.jpg"
import star from "../images/star.png"

export default[
    {
        id:1,
        img: piolho1, 
        star: star,
        rating: "5.0", 
        reviewCount: 350 ,
        country: "BR",
        title: "Piolhinho sendo Piolho versão 1", 
        price: 500,
        openSpot: 0,
        location: "online",
    },
    {
        id:2,
        img: piolho2,
        star:star,
        rating: "5.0", 
        reviewCount: 350, 
        country:"BR",
        title:"Piolhinho sendo Piolho versão 2", 
        price:500,
        openSpot: 1,
        // location: "online",
    },
    {
        id:3,
        img:piolho3,
        star:star,
        rating:"5.0", 
        reviewCount:350, 
        country:"BR",
        title:"Piolhinho sendo Piolho versão 3",
        price:500,
        openSpot: 1,
        location: "online",
    },
    {
        id:4,
        img: piolho2,
        star:star,
        rating: "5.0", 
        reviewCount: 350, 
        country:"BR",
        title:"Piolhinho sendo Piolho versão 2", 
        price:500,
        openSpot: 2,
        location: "online",
    },
    {
        id:5,
        img: piolho2,
        star:star,
        rating: "5.0", 
        reviewCount: 350, 
        country:"BR",
        title:"Piolhinho sendo Piolho versão 2", 
        price:500,
        openSpot: 0,
        location: "online",
    },
    {
        id:6,
        img: piolho2,
        star:star,
        rating: "5.0", 
        reviewCount: 350, 
        country:"BR",
        title:"Piolhinho sendo Piolho versão 2", 
        price:500,
        openSpot: 1,
        // location: "online",
    }
]